### ISSUE TITLE
how to use ssr in linux server? 

### ISSUE THREAD

**Issue by tscswcn** [dongkaipo/ssr#1]
I have install your ssr client  and 
ssr config add ssr_url 

I have use ssr_url  for SSR client within windows client and  successed.
I want to know how to test in linux server??

**Comment by dongkaipo** [comment]
v2ray 方便一些吧，直接安装配置下就可以了。
我记得 sslocal -c /配置文件.json 就可以启动
然后 export https_proxy=http://127.0.0.1:1080 http_proxy=http://127.0.0.1:1080 all_proxy=socks5://127.0.0.1:1080
就成

**Comment by tscswcn** [comment]
谢谢，我的linux 不是有桌面的那种，这样也行吗？

**Comment by dongkaipo** [comment]
> 谢谢，我的linux 不是有桌面的那种，这样也行吗？

对，没有桌面也可以用的
